spring:
  datasource:
    url: jdbc:mysql://202.191.56.11:3307/test
    username: root
    password: Hust20232
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: true

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days

# Keycloak
keycloak:
  realm: master
  auth-server-url: http://localhost:7080
  ssl-required: none
  resource: keycloak_test
  use-resource-role-mappings: true
  bearer-only: true
  cors: true
  principal-attribute: admin
  username: admin
  password: admin
  credentials:
    secret: FzTRUSLx8jrToAYRX1MNtbdAnv712Ugy